### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by cwhitney** [cwhitney/GoldsprintsFx#1]
- [x] Use system clock for timers (cosmetic)
- [x] Finish implementing graphics for racers
- [x] Add hardware connection status indicator
- [x] Add option to reconnect hardware if disconnected
- [x] Implement mph
- [x] Auto save settings on exit
- [x] Ability to run a race with less than 4 racers
- [x] Implement winner graphics
- [ ] Implement false start graphics

**Comment by ehusar** [comment]
I have a suggestion to add the checklist.  Change the name of this project to something other than GoldsprintsFX.  What do you think?

**Comment by lukeorland** [comment]
i had the same thought.

**Comment by cwhitney** [comment]
Totally open to it! Let's come up with something.

**Comment by ehusar** [comment]
The only reason I ask is because I am the developer of GoldsprintsFX. :)

**Comment by jonfen** [comment]
@ehusar open source it!

**Comment by cwhitney** [comment]
Definitely not going to be named this, an FPO name for sure. Going to open a new issue for this! [Throw suggestions here](https://github.com/cwhitney/GoldsprintsFx/issues/2)

**Comment by ehusar** [comment]
The first name and comes to mind is GoldsprintsPlus+  Or Maybe Goldsprints+Plus
